### PR TITLE
Fixed the sample that goes with salti

### LINKED ISSUE #4: Fix the sample that goes with salti

### PR DESCRIPTION
**Pull request by andrew-aladev**
fixes #4 

Fixed sample, fixed acl schema, added strip slashes option and its test.

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/salti/7)

### CODE REVIEW

**Comment by yaronyg** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[.gitignore, line 42 [r1]](https://reviewable.io:443/reviews/thaliproject/salti/7#-KN9ZcxS3Jdy9WpkT3tX:-KN9ZcxTGbjnDlO4h2TO:963178740) ([raw file](https://github.com/thaliproject/salti/blob/e20e201419c7876f49158518b1540a35af470954/.gitignore#L42)):_

> ```
> db/*
> sample/db/*
> !sample/db/.gitkeep
> ```

gitkeep is a made up convention as far as I'm aware. If we need a particular directory to exist than rather than shoving it into the repo can't we just create it as part of an install script?

---

_[sample/server.js, line 18 [r1]](https://reviewable.io:443/reviews/thaliproject/salti/7#-KN9aX2Go82ITg74ljeq:-KN9aX2Go82ITg74ljer:816644268) ([raw file](https://github.com/thaliproject/salti/blob/e20e201419c7876f49158518b1540a35af470954/sample/server.js#L18)):_

> ``` JavaScript
> var webAppPort = normalizePort(process.env.PORT || '3000');
> 
> var serverCommonOptions = {
> ```

If we are using psk then we don't need the public key certs anymore. They were required in the old days because of a bug. So we can pull out the PEM and files, the code to load them, the assigns, etc.

---

_[test/test-trailing-slash.js, line 118 [r1]](https://reviewable.io:443/reviews/thaliproject/salti/7#-KN9c2w13ZM2b25xlwh7:-KN9c2w13ZM2b25xlwh8:1847528808) ([raw file](https://github.com/thaliproject/salti/blob/e20e201419c7876f49158518b1540a35af470954/test/test-trailing-slash.js#L118)):_

> ``` JavaScript
>         .expect(401, done);
>     })
>     it('/bar/ should be 200', function(done) {
> ```

I would throw in a test using a URL encoded / just to be paranoid and make sure we don't treat it as part of the path segment.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/salti/7)_

**Comment by yaronyg** [comment]
@andrew-aladev - It would be good if we could the areas of the code that aren't being tested (e.g. https://coveralls.io/builds/7100824/source?filename=lib%2Findex.js) covered with the obvious exception of line 60.

---

Reviewed 4 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[sample/server.js, line 25 [r3]](https://reviewable.io:443/reviews/thaliproject/salti/7#-KNDeNuVySKlJhhPLPyD:-KNDeNuWXc7ufOxdKqTv:1939662904) ([raw file](https://github.com/thaliproject/salti/blob/1287a8388d1e434fb568c9d7200c191c162f4113/sample/server.js#L25)):_

> ``` JavaScript
> 
> var pouchDBName = 'db';
> if (! fs.existsSync('./' + pouchDBName)){
> ```

This code shouldn't be necessary. PouchDB should create the directory for the DB.

---

_[sample/server.js, line 28 [r3]](https://reviewable.io:443/reviews/thaliproject/salti/7#-KNDe1c7pVC2ORqBBSJ9:-KNDe1c7pVC2ORqBBSJA:86169367) ([raw file](https://github.com/thaliproject/salti/blob/1287a8388d1e434fb568c9d7200c191c162f4113/sample/server.js#L28)):_

> ``` JavaScript
>     fs.mkdirSync('./' + pouchDBName);
> }
> var pbsetup = PouchDB.defaults({ prefix: './' + pouchDBName + '/' });
> ```

Prefix is supposed to identify the directory where the file can be found, not the file name itself. PouchDB will handle creating any directories it needs to hold the database. Prefix is just to tell it where to put that directory if you don't want it to use the current directory.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/salti/7#-:-KNDaw4OMTTbhT1bE_O9:2087802523)_

**Comment by andrew-aladev** [comment]
Pouch DB will create dir for its db. But it will throw an exception If its prefix dir does not exist.
Many directories will be auto created. I think previous developer used prefix to hide these auto created directories. Should we remove prefix directory? Thank you.

**Comment by yaronyg** [comment]
:lgtm:

I think the prefix directory is fine.

---

Reviewed 1 of 3 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/salti/7#-:-KNJXxG7J1kit9YGoS-g:1241635002)_

**Pull request merged**
