### PR TITLE
Fixed salti path resolution

### LINKED ISSUE #10: Remove the prefix option and related code form Salti

### PR DESCRIPTION
**Pull request by andrew-aladev**
1. Added schema check.
2. Path resolution simplified.
3. Removed irrational regexp from thali id.
4. Both DB name and prefix has been cutted before actual path check. It shouldn't create any problem in future with any spec #9.

I think this closes previous problem with db prefix. Closes #10

---

This change is [Reviewable](https://reviewable.io/reviews/thaliproject/salti/11)

### CODE REVIEW

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/index.js, line 237 [r1]](https://reviewable.io:443/reviews/thaliproject/salti/11#-KORx_eFXyh7z5klSUh4:-KORx_eFXyh7z5klSUh5:b-99gsfl) ([raw file](https://github.com/thaliproject/salti/blob/a0c3b1e62096b5a8717f4943c5a211feb4810938/lib/index.js#L237)):_

> ``` JavaScript
>     return false;
>   }
>   this.path = this.path.substring(this.dbPrefix.length);
> ```

NB: Personally I think that changing a state variable of a class as a side effect of a function isn't terribly discoverable. I would probably have designed this function to either return null if there is no path match or otherwise return the path and then set this.path higher up. You can put the whole thing into the if statement so you don't even need an extra line.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/salti/11#-:-KOS-KNqnu_DJaVRmypZ:bnfp4nl)_

**Comment by yaronyg** [comment]
This should be closed today

**Comment by andrew-aladev** [comment]
Year, thank you. It looks perfect to rename `cutDBPrefix` to `getPathWithoutPrefix` and proceed the check with cutted path as local variable.

**Comment by yaronyg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[lib/index.js, line 118 [r2]](https://reviewable.io:443/reviews/thaliproject/salti/11#-KOgYHH_cMOyQmAL6t65:-KOgYHH_cMOyQmAL6t66:b3se6sz) ([raw file](https://github.com/thaliproject/salti/blob/1293fdba8155328f7ea8957169d89aaff453c70b/lib/index.js#L118)):_

> ``` JavaScript
>   // Next section deals with
>   // /{:db}/{:id}, /{:db}/_local/{:id} and /{:db}/{:id}/attachment stuff.
>   var cuttedPath = this.getPathWithoutPrefix();
> ```

NB:/cuttedPath/cutPath/

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/thaliproject/salti/11#-:-KOgYNi-hesKjnKYzQKD:bnfp4nl)_

**Comment by andrew-aladev** [comment]
https://www.npmjs.com/~andrew-aladev

**Pull request merged**
